AllCops:
  NewCops: enable
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

# Style/ConditionalAssignment:
#   Enabled: false
# Style/RedundantReturn:
#   Enabled: false
Style/Documentation:
  Enabled: false
# Style/WordArray:
#   Enabled: false
# Metrics/AbcSize:
#   Enabled: false
# Style/MutableConstant:
#   Enabled: false
# Style/SignalException:
#   Enabled: false
# Metrics/CyclomaticComplexity:
#   Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
